spring:
  application:
    name: todo-list
  data:
    mongodb:
      database: to-do-lists
      uri: mongodb://root:123456789@mongo-db:27017/to-do-lists?authSource=admin
springdoc:
  api-docs:
    path: /todo-list/docs
  swagger-ui:
    path: /todo-list/api-docs/
server:
  port: 8400