spring:
  application:
    name: todo-list
  data:
    mongodb:
      database: to-do-lists
      uri: mongodb://localhost:27017/to-do-lists
springdoc:
  api-docs:
    path: /todo-list/docs
  swagger-ui:
    path: /todo-list/api-docs/
server:
  port: 8400